### ISSUE TITLE
A UAC shield Krypton button 

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.7#16]
Self explanatory

**Comment by herledant** [comment]
Hello Wagnerp,
Coult you explain me how it's work?
I try to use it and when i click it, the elevation doesn't fire.
I've set the elevationonclieck to true

**Comment by Wagnerp** [comment]
Yes sure, I don't know how the VB syntax is, but in the button click event you put:

`ElevateProcessWithAdministrativeRights(**Your process here**)`

**Comment by herledant** [comment]
ok thank's.
Is there any help  that i can read to understand how tu use all the controls you bring with the extended krypton?

**Comment by Wagnerp** [comment]
Hi @herledant 

Unfortunately not, but if you need any help, just post a question here and I can help you.
